### ISSUE TITLE
fix url for capture-download

### ISSUE THREAD

**Issue by dschoeni** [probr-uzh/probr-core#13]
fix this:

![image](https://cloud.githubusercontent.com/assets/1913623/10879058/f775248c-8151-11e5-9df1-64607d4e12bf.png)

**Comment by dcale** [comment]
fixed: when serving behind a proxy, simply put this in your settings.py:

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
