### ISSUE TITLE
ordering not working on rest-framework endpoints

### ISSUE THREAD

**Issue by dschoeni** [probr-uzh/probr-core#2]
Order won't work according to http://www.django-rest-framework.org/api-guide/filtering/#orderingfilter

Steps to Reproduce:
- Start probr-core locally
- GET http://localhost:8080/api/captures/?ordering=creation_timestamp delivers same result as GET http://localhost:8080/api/captures/?-ordering=creation_timestamp

**Comment by dcale** [comment]
Fixed in dev branch, will merge to master if no one complains
