### ISSUE TITLE
Signal strength is always -256

### ISSUE THREAD

**Issue by schollz** [probr-uzh/probr-core#24]
Awesome project! I'm having a little trouble getting the signal strength (either from tcpdump or from the parsing). As a minimal test, I'm using

```
tcpdump -e -ni (myinterface) -s 0 -w capture-%s.pcap -G 5 -tttt -vvvv type mgt subtype probe-req
```

and then I parse it using a scaled down version of your code: [parse_packet.py](https://gist.githubusercontent.com/schollz/8bee725dc82592dec5060970c13b229d/raw/f15116b96532ead76261043a0518d5f343c6b2d2/packets-tcpdump.py) which results in something like the following:

```
{'inserted_at': datetime.datetime(2017, 11, 25, 10, 8, 46, 667550), 'mac_address_src': b'ac3743a88dc7', 'time': datetime.datetime(2017, 11, 25, 9, 59, 32, 248626), 'mac_address_dst': b'ffffffffffff', 'signal_strength': -256, 'ssid': b''}
```

where the `signal_strength` is always -256. However, I have some other code for doing this in scapy: [packets.py](https://gist.github.com/schollz/ba151ba1fbb1bd433fd523ac9502947a) which will give the following correct RSSI for that same MAC:

```
('ac:37:43:a8:8d:c7', 'a0:63:91:2b:9e:65', '-75')
('ac:37:43:a8:8d:c7', 'a0:63:91:2b:9e:65', '-72')
('ac:37:43:a8:8d:c7', 'a0:63:91:2b:9e:65', '-82')
('ac:37:43:a8:8d:c7', 'a0:63:91:2b:9e:65', '-82')
```

so I know that its not my interface. Is it a problem with `tcpdump`? I also tried adding the `-y IEEE802_11_RADIO` flag but that had the same problem. Could it be a problem with the parsing? Please let me know thanks!

(Also full disclosure, I built something very similar awhile ago: https://github.com/schollz/find-lf, but I think your project is above and beyond what I did, great job!)

**Comment by randomly123** [comment]
I have the same issue folks. Signal strength is 256, all the time

**Comment by dcale** [comment]
Hi @randomly123 @schollz the issue is that the library we're using to read the radiotap header is not reading correctly the headers of all devices. I experience the issue when using a nexmon rpi3. Long story short, the handler code is easy to update and there will be a pull request soon, fixing the issue.

**Comment by schollz** [comment]
@dcale, That's great. Looking forward to it!

**Comment by rrodstein** [comment]
hi dcale, have you been able to get probr-analysis to see the pcaps or live managed devices? if yes could you please give us some tips? we can get both core and analysis, and core collecting pcaps from manged devices, but analysis sees no data. thank you!

**Comment by dcale** [comment]
@schollz the issue should be fixed now

@rrodstein please open a ticket with the actual issues. We do have a running version of this running in production including analysis showing all packets flying in.

**Comment by schollz** [comment]
@dcale thanks! I look forward to giving it a try!
