### ISSUE TITLE
can't post captures to probe-core or see in analysis

### ISSUE THREAD

**Issue by stormdog10** [probr-uzh/probr-core#29]
hi 

I have both probr-core and probe-analysis working from docker but i can't get the packet captures from my pi running kali to probe-core !!! when i issue the command below on my kali raspberry pi

# Upload Existing
for file in captures/*.pcap
do
    post_file '/api-device/device-captures/' "$file" && rm "$file"
done

i get bash: post_file command not found

i feel i am close to getting this woking!
 
can you help???

**Comment by stormdog10** [comment]
Eventually got there with it😜

**Comment by mohbandy** [comment]
I am excited to see you got this up and running on your pi! I have been working to try to get this up and running as well using raspbian (not kali). Did you have to do anything in addition to what the directions/readme stated to get probr-core working?

For example I had modified my /etc/hosts file so when the code looked for postgres it routed to localhost
