### ISSUE TITLE
performance-problems on statuses/?device

### ISSUE THREAD

**Issue by dschoeni** [probr-uzh/probr-core#8]
Some REST-Endpoints on Core show massive performance problem after a certain run-time. I suspect certain specific endpoints are involved in this, specifically `statuses/?device=UUID&limit=10` which takes about 2 seconds after reloading to give a result. I guess if the database includes lots and lots of statuses, this becomes a problem. 

Maybe we should either
- Add a TTL to statuses (as they are increasingly unimportant after time)
- Keep view for the last 10 statuses of each device to prevent going over the ORM and potentially inefficient queries

**Comment by dcale** [comment]
closed with 3444db5b27899ce02c02
